version: '3'
services:
  web:
    image: tic-tac-toe:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: tic-tac-toe
        awslogs-region: us-east-1
        awslogs-stream-prefix: web