version: '3'

services:
  app:
    image: 'tic-tac-toe:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tic-tac-toe
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresdb:
    image: 'postgres:13.1-alpine'
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
